# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
